### ISSUE TITLE
бесконечная загрузка

### ISSUE THREAD

**Issue by sexplov** [Soto4ka37/Yandex-Music-RPC-Lite#1]
бесконечная загрузка при коннекте (последняя версия)
на предыдущей версии в статусе отображался только один трек, даже когда играли другие

**Comment by Soto4ka37** [comment]
- Проверь наличие токена в %appdata%/YM-RPC/data.json, если он на месте попробуй удалить его и запустить программу
- Проверь корректно ли отображается трек в [`классической версии`](https://github.com/Soto4ka37/Yandex-Music-RPC-Lite/releases/download/v7.2/RPC.exe), она заведомо рабочая.
- Ещё если ты слушаешь музыку в браузере трек может не определяться - это уже проблема на стороне яндекса не зависящая от меня.

Если в классической версии всё отображается корректно, а в новой - нет напиши мне в дискорд или телеграм: @soto4ka37 
В настоящий момент слишком мало информации о проблеме.

**Comment by sexplov** [comment]
> * Проверь наличие токена в %appdata%/YM-RPC/data.json, если он на месте попробуй удалить его и запустить программу
> * Проверь корректно ли отображается трек в [`классической версии`](https://github.com/Soto4ka37/Yandex-Music-RPC-Lite/releases/download/v7.2/RPC.exe), она заведомо рабочая.
> * Ещё если ты слушаешь музыку в браузере трек может не определяться - это уже проблема на стороне яндекса не зависящая от меня.
> 
> Если в классической версии всё отображается корректно, а в новой - нет напиши мне в дискорд или телеграм: @Soto4ka37 Т.к. нужно больше информации о проблеме

ну, вроде как заработала, будто бы, но спустя полчаса зависло на одном треке и не обновляется больше. Что классическая версия, что ласт - разницы в этом плане нет.
"[RPC] Загружены настройки из settings.ini
[RPC] Смена трека: GONE.Fludd - ХУДРИЧ (2:18)
[RPC] Трек не изменился."

**Comment by Soto4ka37** [comment]
> ну, вроде как заработала, будто бы, но спустя полчаса зависло на одном треке и не обновляется больше. Что классическая версия, что ласт - разницы в этом плане нет. "[RPC] Загружены настройки из settings.ini [RPC] Смена трека: GONE.Fludd - ХУДРИЧ (2:18) [RPC] Трек не изменился."

Если в классической версии то же самое - то это уже у яндекса приколы

**Comment by Soto4ka37** [comment]
Если будет бесконечная загрузка запусти версию с откладкой https://www.soto4ka.space/file/debugged.exe она должна показать ошибку в консоли
