### ISSUE TITLE
пишет бесконечно, что слушаю мою волну

### ISSUE THREAD

**Issue by Sk8Maf1a** [Soto4ka37/Yandex-Music-RPC-Lite#2]
как только запускаю программу сразу отображается, что слушаю мою волну, даже если не слушаю ничего или слушаю своё любимое
![image](https://github.com/Soto4ka37/Yandex-Music-RPC-Lite/assets/96859213/a5130481-3f61-4c9b-a83e-a26a99a232b8)

**Comment by Sk8Maf1a** [comment]
в стандартной версии тоже самое

**Comment by Sk8Maf1a** [comment]
использую
https://github.com/Soto4ka37/Yandex-Music-RPC-Lite/releases/tag/v8.2.1

**Comment by Soto4ka37** [comment]
Это у яндекса приколы, к сожалению не могу ничего поделать с этим. На разных аккаунтах поведение их апи разное и я не знаю что с этим делать. Такие проблемы начались ещё в конце лета и продолжются до сих пор. 

Остаётся только надеяться что яндексы починят апи 🙁

**Comment by Soto4ka37** [comment]
Чаще всего такие проблемы возникают при использовании браузрной версии яндекс музыки
