### ISSUE TITLE
Проблема с приоритетом | На стороне Яндекса

### ISSUE THREAD

**Issue by ThePud1ng** [Soto4ka37/Yandex-Music-RPC-Lite#3]
Почему-то игнорирует что браузер, что приложение для ПК и берет треки с приложения на телефоне (даже если там ничего не запущено, то просто последний трек оттуда зацикливает)

**Comment by Soto4ka37** [comment]
Проблема на стороне Яндекса, не могу ничем помочь 🙁

На разных аккаунтах поведение их апи разное. У меня схожая проблема с игнорированием браузера в пользу мобильного приложения, но пк версия имеет схожий приоритет с мобильной.

Подобные проблемы начались в ещё конце августа.
Остаётся только надеяться, что Яндексы починят апи.

**Comment by sexplov** [comment]
то же самое..

**Comment by sexplov** [comment]
> Проблема на стороне Яндекса, не могу ничем помочь 🙁
> 
> На разных аккаунтах поведение их апи разное. У меня схожая проблема с игнорированием браузера в пользу мобильного приложения, но пк версия имеет схожий приоритет с мобильной.
> 
> Подобные проблемы начались ещё в конце августа. Остаётся только надеяться, что Яндексы починят апи.

а ты можешь обратиться в поддержку яндекса с этим? 
думаю ты, как разработчик, сможешь лучше все объяснить, чем мы. Или твое творение нелегально?

**Comment by Soto4ka37** [comment]
> а ты можешь обратиться в поддержку яндекса с этим? думаю ты, как разработчик, сможешь лучше все объяснить, чем мы. Или твое творение нелегально?

По поводу легальности в душе не чаю, но попробовать стоит)

**Comment by Soto4ka37** [comment]
Яндекс починили API, всё должно работать корректно
