### ISSUE TITLE
Автозапуск

### ISSUE THREAD

**Issue by skvizxc** [Soto4ka37/Yandex-Music-RPC-Lite#4]
Думаю, что было бы славно добавить возможность к автозапуску приложения в трее вместе с системой. Само приложение яндекс музыки имеет такую возможность, думаю было бы удобно, если не нужно было бы тыкать иконку каждый раз вручную)

**Comment by Soto4ka37** [comment]
Автозапуск невозможен так как дискорд запускается значительно дольше скрипта, а при попытке запустить скрипт без активного дискорда он моментально завершится ошибкой.
