### ISSUE TITLE
Вопрос о изменениях

### ISSUE THREAD

**Issue by filitlite** [Soto4ka37/Yandex-Music-RPC-Lite#5]
1. Хотел узнать у вас, будет ли обновление, в котором, при постановления трека на паузу, таймер будет останавливаться и показывать, что трек на паузе.
2. Будет ли возможность, когда-то менять название кнопок или добавлять их (В статусе), без влезания в код
Заранее спасибо за ответ.

**Comment by Soto4ka37** [comment]
1. Пауза невозможна из-за того, что Яндекс не хранит  информацию о состоянии плеера.
2. Кнопки попробую сделать как будет время. С этим не должно возникнуть проблем.

**Comment by Soto4ka37** [comment]
Редактор кнопок сделал. Обновление выложу завтра.
![image](https://github.com/Soto4ka37/Yandex-Music-RPC-Lite/assets/62742200/5d462935-5ce0-4ff7-912c-75810c16e34b)
